apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  namespace: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: 033488708439.dkr.ecr.eu-west-2.amazonaws.com/promptx-admin:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: admin
spec:
  selector:
    app: admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
